export const budgets = [
  {
    id: '1',
    category: 'Shopping',
    limit: 500,
    spent: 100,
    left: 500,
    notice: '🔥 Your  burn rate for Shopping is on track',
    icon: '/assets/budget-icons/shopping.svg',
    color: {
      active: '#5C9AF7',
      background: 'rgba(92, 154, 247, 0.2)',
    },
    currency: '$',
    title: 'Shopping',
  },
  {
    id: '2',
    category: 'Food & Drinks',
    limit: 2000,
    spent: 1500,
    left: 500,
    notice: '😱 Watch your Food & Drinks burn rate',
    icon: '/assets/budget-icons/food.svg',
    color: {
      active: '#5CF7AD',
      background: 'rgba(92, 247, 173, 0.2)',
    },
    currency: '$',
    title: 'Food & Drinks',
  },
  {
    id: '3',
    category: 'Transportation',
    limit: 150,
    spent: 65,
    icon: '/assets/budget-icons/transport.svg',
    color: {
      active: '#D85CF7',
      background: 'rgba(216, 92, 247, 0.2)',
    },
    currency: '$',
    title: 'Transportation',
  },
  {
    id: '4',
    category: 'Entertainment',
    limit: 100,
    spent: 15,
    icon: '/assets/budget-icons/entertainment.svg',
    color: {
      active: '#FF8787',
      background: 'rgba(255, 135, 135, 0.2)',
    },
    currency: '$',
    title: 'Entertainment',
  },
  {
    id: '5',
    category: 'Gift',
    limit: 300,
    spent: 150,
    left: 500,
    notice: '🔥 Your  burn rate for Gift is on track',
    icon: '/assets/budget-icons/gift.svg',
    color: {
      active: '#A199FF',
      background: 'rgba(161, 153, 255, 0.2)',
    },
    currency: '$',
    title: 'Gift',
  },
  {
    id: '6',
    category: 'Pet',
    limit: 200,
    spent: 180,
    left: 500,
    notice: '🔥 Your  burn rate for Pet is on track',
    icon: '/assets/budget-icons/pet.svg',
    color: {
      active: '#FEBD80',
      background: 'rgba(254, 189, 128, 0.2)',
    },
    currency: '$',
    title: 'Pet',
  },
  {
    id: '7',
    category: 'Education',
    limit: 500,
    spent: 350,
    left: 500,
    notice: '🔥 Your  burn rate for Education is on track',
    icon: '/assets/budget-icons/education.svg',
    color: {
      active: '#ffffff',
      background: 'rgba(255, 255, 255, 0.2)',
    },
    currency: '$',
    title: 'Education',
  },
];
